// Auto-generated list of PG image assets

export const PG_ART_AND_CRAFT_IMAGES = [
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_01.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_02.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_03.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_04.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_05.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_06.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_07.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_08.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_09.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_10.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_11.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_12.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_13.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_14.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_15.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_16.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_17.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_18.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_19.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_20.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_21.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_22.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_23.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_24.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_25.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_26.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_27.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_28.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_29.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_30.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_31.jpg"),
  require("./PG_ART_AND_CRAFT_IMAGES/Art_craft_Page_32.jpg"),
];
console.log('🔍 First image require result:', PG_ART_AND_CRAFT_IMAGES[0]);
console.log('🔍 Type of first image:', typeof PG_ART_AND_CRAFT_IMAGES[0]);

export const PG_EVS_IMAGES = [
  require("./EVS/EVS_Page_01.jpg"),
  require("./EVS/EVS_Page_02.jpg"),
  require("./EVS/EVS_Page_03.jpg"),
  require("./EVS/EVS_Page_04.jpg"),
  require("./EVS/EVS_Page_05.jpg"),
  require("./EVS/EVS_Page_06.jpg"),
  require("./EVS/EVS_Page_07.jpg"),
  require("./EVS/EVS_Page_08.jpg"),
  require("./EVS/EVS_Page_09.jpg"),
  require("./EVS/EVS_Page_10.jpg"),
  require("./EVS/EVS_Page_11.jpg"),
  require("./EVS/EVS_Page_12.jpg"),
  require("./EVS/EVS_Page_13.jpg"),
  require("./EVS/EVS_Page_14.jpg"),
  require("./EVS/EVS_Page_15.jpg"),
  require("./EVS/EVS_Page_16.jpg"),
  require("./EVS/EVS_Page_17.jpg"),
  require("./EVS/EVS_Page_18.jpg"),
  require("./EVS/EVS_Page_19.jpg"),
  require("./EVS/EVS_Page_20.jpg"),
  require("./EVS/EVS_Page_21.jpg"),
  require("./EVS/EVS_Page_22.jpg"),
  require("./EVS/EVS_Page_23.jpg"),
  require("./EVS/EVS_Page_24.jpg"),
  require("./EVS/EVS_Page_25.jpg"),
  require("./EVS/EVS_Page_26.jpg"),
  require("./EVS/EVS_Page_27.jpg"),
  require("./EVS/EVS_Page_28.jpg"),
  require("./EVS/EVS_Page_29.jpg"),
  require("./EVS/EVS_Page_30.jpg"),
  require("./EVS/EVS_Page_31.jpg"),
  require("./EVS/EVS_Page_32.jpg"),
  require("./EVS/EVS_Page_33.jpg"),
  require("./EVS/EVS_Page_34.jpg"),
  require("./EVS/EVS_Page_35.jpg"),
  require("./EVS/EVS_Page_36.jpg"),
  require("./EVS/EVS_Page_37.jpg"),
  require("./EVS/EVS_Page_38.jpg"),
  require("./EVS/EVS_Page_39.jpg"),
  require("./EVS/EVS_Page_40.jpg"),
  require("./EVS/EVS_Page_41.jpg"),
  require("./EVS/EVS_Page_42.jpg"),
  require("./EVS/EVS_Page_43.jpg"),
  require("./EVS/EVS_Page_44.jpg"),
  require("./EVS/EVS_Page_45.jpg"),
  require("./EVS/EVS_Page_46.jpg"),
  require("./EVS/EVS_Page_47.jpg"),
  require("./EVS/EVS_Page_48.jpg"),
  require("./EVS/EVS_Page_49.jpg"),
  require("./EVS/EVS_Page_50.jpg"),
  require("./EVS/EVS_Page_51.jpg"),
  require("./EVS/EVS_Page_52.jpg"),
  require("./EVS/EVS_Page_53.jpg"),
  require("./EVS/EVS_Page_54.jpg"),
  require("./EVS/EVS_Page_55.jpg"),
  require("./EVS/EVS_Page_56.jpg"),
] ;

export const PG_ENGLISH_IMAGES = [
  require("./English/English_Page_01.jpg"),
  require("./English/English_Page_02.jpg"),
  require("./English/English_Page_03.jpg"),
  require("./English/English_Page_04.jpg"),
  require("./English/English_Page_05.jpg"),
  require("./English/English_Page_06.jpg"),
  require("./English/English_Page_07.jpg"),
  require("./English/English_Page_08.jpg"),
  require("./English/English_Page_09.jpg"),
  require("./English/English_Page_10.jpg"),
  require("./English/English_Page_11.jpg"),
  require("./English/English_Page_12.jpg"),
  require("./English/English_Page_13.jpg"),
  require("./English/English_Page_14.jpg"),
  require("./English/English_Page_15.jpg"),
  require("./English/English_Page_16.jpg"),
  require("./English/English_Page_17.jpg"),
  require("./English/English_Page_18.jpg"),
  require("./English/English_Page_19.jpg"),
  require("./English/English_Page_20.jpg"),
  require("./English/English_Page_21.jpg"),
  require("./English/English_Page_22.jpg"),
  require("./English/English_Page_23.jpg"),
  require("./English/English_Page_24.jpg"),
  require("./English/English_Page_25.jpg"),
  require("./English/English_Page_26.jpg"),
  require("./English/English_Page_27.jpg"),
  require("./English/English_Page_28.jpg"),
  require("./English/English_Page_29.jpg"),
  require("./English/English_Page_30.jpg"),
  require("./English/English_Page_31.jpg"),
  require("./English/English_Page_32.jpg"),
  require("./English/English_Page_33.jpg"),
  require("./English/English_Page_34.jpg"),
  require("./English/English_Page_35.jpg"),
  require("./English/English_Page_36.jpg"),
  require("./English/English_Page_37.jpg"),
  require("./English/English_Page_38.jpg"),
  require("./English/English_Page_39.jpg"),
  require("./English/English_Page_40.jpg"),
  require("./English/English_Page_41.jpg"),
  require("./English/English_Page_42.jpg"),
  require("./English/English_Page_43.jpg"),
  require("./English/English_Page_44.jpg"),
  require("./English/English_Page_45.jpg"),
  require("./English/English_Page_46.jpg"),
  require("./English/English_Page_47.jpg"),
  require("./English/English_Page_48.jpg"),
  require("./English/English_Page_49.jpg"),
  require("./English/English_Page_50.jpg"),
  require("./English/English_Page_51.jpg"),
  require("./English/English_Page_52.jpg"),
  require("./English/English_Page_53.jpg"),
  require("./English/English_Page_54.jpg"),
  require("./English/English_Page_55.jpg"),
  require("./English/English_Page_56.jpg"),
];

export const PG_MATHS_IMAGES = [
  require("./Maths/Maths_Page_01.jpg"),
  require("./Maths/Maths_Page_02.jpg"),
  require("./Maths/Maths_Page_03.jpg"),
  require("./Maths/Maths_Page_04.jpg"),
  require("./Maths/Maths_Page_05.jpg"),
  require("./Maths/Maths_Page_06.jpg"),
  require("./Maths/Maths_Page_07.jpg"),
  require("./Maths/Maths_Page_08.jpg"),
  require("./Maths/Maths_Page_09.jpg"),
  require("./Maths/Maths_Page_10.jpg"),
  require("./Maths/Maths_Page_11.jpg"),
  require("./Maths/Maths_Page_12.jpg"),
  require("./Maths/Maths_Page_13.jpg"),
  require("./Maths/Maths_Page_14.jpg"),
  require("./Maths/Maths_Page_15.jpg"),
  require("./Maths/Maths_Page_16.jpg"),
  require("./Maths/Maths_Page_17.jpg"),
  require("./Maths/Maths_Page_18.jpg"),
  require("./Maths/Maths_Page_19.jpg"),
  require("./Maths/Maths_Page_20.jpg"),
  require("./Maths/Maths_Page_21.jpg"),
  require("./Maths/Maths_Page_22.jpg"),
  require("./Maths/Maths_Page_23.jpg"),
  require("./Maths/Maths_Page_24.jpg"),
  require("./Maths/Maths_Page_25.jpg"),
  require("./Maths/Maths_Page_26.jpg"),
  require("./Maths/Maths_Page_27.jpg"),
  require("./Maths/Maths_Page_28.jpg"),
  require("./Maths/Maths_Page_29.jpg"),
  require("./Maths/Maths_Page_30.jpg"),
  require("./Maths/Maths_Page_31.jpg"),
  require("./Maths/Maths_Page_32.jpg"),
  require("./Maths/Maths_Page_33.jpg"),
  require("./Maths/Maths_Page_34.jpg"),
  require("./Maths/Maths_Page_35.jpg"),
  require("./Maths/Maths_Page_36.jpg"),
  require("./Maths/Maths_Page_37.jpg"),
  require("./Maths/Maths_Page_38.jpg"),
  require("./Maths/Maths_Page_39.jpg"),
  require("./Maths/Maths_Page_40.jpg"),
  require("./Maths/Maths_Page_41.jpg"),
  require("./Maths/Maths_Page_42.jpg"),
  require("./Maths/Maths_Page_43.jpg"),
  require("./Maths/Maths_Page_44.jpg"),
  require("./Maths/Maths_Page_45.jpg"),
  require("./Maths/Maths_Page_46.jpg"),
  require("./Maths/Maths_Page_47.jpg"),
  require("./Maths/Maths_Page_48.jpg"),
  require("./Maths/Maths_Page_49.jpg"),
  require("./Maths/Maths_Page_50.jpg"),
  require("./Maths/Maths_Page_51.jpg"),
  require("./Maths/Maths_Page_52.jpg"),
  require("./Maths/Maths_Page_53.jpg"),
  require("./Maths/Maths_Page_54.jpg"),
  require("./Maths/Maths_Page_55.jpg"),
  require("./Maths/Maths_Page_56.jpg"),
  require("./Maths/Maths_Page_57.jpg"),
  require("./Maths/Maths_Page_58.jpg"),
  require("./Maths/Maths_Page_59.jpg"),
  require("./Maths/Maths_Page_60.jpg"),
] as const;

export const PG_PATTERN_IMAGES = [
  require("./Pattern/Pattern_Page_01.jpg"),
  require("./Pattern/Pattern_Page_02.jpg"),
  require("./Pattern/Pattern_Page_03.jpg"),
  require("./Pattern/Pattern_Page_04.jpg"),
  require("./Pattern/Pattern_Page_05.jpg"),
  require("./Pattern/Pattern_Page_06.jpg"),
  require("./Pattern/Pattern_Page_07.jpg"),
  require("./Pattern/Pattern_Page_08.jpg"),
  require("./Pattern/Pattern_Page_09.jpg"),
  require("./Pattern/Pattern_Page_10.jpg"),
  require("./Pattern/Pattern_Page_11.jpg"),
  require("./Pattern/Pattern_Page_12.jpg"),
  require("./Pattern/Pattern_Page_13.jpg"),
  require("./Pattern/Pattern_Page_14.jpg"),
  require("./Pattern/Pattern_Page_15.jpg"),
  require("./Pattern/Pattern_Page_16.jpg"),
  require("./Pattern/Pattern_Page_17.jpg"),
  require("./Pattern/Pattern_Page_18.jpg"),
  require("./Pattern/Pattern_Page_19.jpg"),
  require("./Pattern/Pattern_Page_20.jpg"),
  require("./Pattern/Pattern_Page_21.jpg"),
  require("./Pattern/Pattern_Page_22.jpg"),
  require("./Pattern/Pattern_Page_23.jpg"),
  require("./Pattern/Pattern_Page_24.jpg"),
  require("./Pattern/Pattern_Page_25.jpg"),
  require("./Pattern/Pattern_Page_26.jpg"),
  require("./Pattern/Pattern_Page_27.jpg"),
  require("./Pattern/Pattern_Page_28.jpg"),
] as const;

export const PG_RHYMES_AND_STORIES_IMAGES = [
  require("./Rhymes & Stories/Rhymes & Stories_Page_01.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_02.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_03.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_04.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_05.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_06.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_07.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_08.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_09.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_10.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_11.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_12.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_13.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_14.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_15.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_16.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_17.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_18.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_19.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_20.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_21.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_22.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_23.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_24.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_25.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_26.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_27.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_28.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_29.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_30.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_31.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_32.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_33.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_34.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_35.jpg"),
  require("./Rhymes & Stories/Rhymes & Stories_Page_36.jpg"),
] as const;
