// Auto-generated Nursery Mapping File
// Generated from directory listing on 2025-10-18

export const NUR_1_20 = [
  require("./Nur_1_20/Nur_1_20_Page_01.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_02.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_03.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_04.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_05.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_06.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_07.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_08.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_09.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_10.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_11.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_12.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_13.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_14.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_15.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_16.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_17.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_18.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_19.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_20.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_21.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_22.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_23.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_24.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_25.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_26.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_27.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_28.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_29.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_30.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_31.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_32.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_33.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_34.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_35.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_36.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_37.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_38.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_39.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_40.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_41.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_42.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_43.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_44.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_45.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_46.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_47.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_48.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_49.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_50.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_51.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_52.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_53.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_54.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_55.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_56.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_57.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_58.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_59.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_60.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_61.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_62.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_63.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_64.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_65.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_66.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_67.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_68.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_69.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_70.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_71.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_72.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_73.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_74.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_75.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_76.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_77.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_78.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_79.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_80.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_81.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_82.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_83.jpg"),
  require("./Nur_1_20/Nur_1_20_Page_84.jpg"),
];

export const NUR_1_20_WORKBOOK = [
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_01.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_02.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_03.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_04.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_05.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_06.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_07.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_08.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_09.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_10.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_11.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_12.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_13.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_14.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_15.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_16.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_17.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_18.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_19.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_20.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_21.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_22.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_23.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_24.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_25.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_26.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_27.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_28.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_29.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_30.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_31.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_32.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_33.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_34.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_35.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_36.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_37.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_38.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_39.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_40.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_41.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_42.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_43.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_44.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_45.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_46.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_47.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_48.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_49.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_50.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_51.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_52.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_53.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_54.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_55.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_56.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_57.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_58.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_59.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_60.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_61.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_62.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_63.jpg"),
  require("./Nur_1_20_workbook/Nur_1_20_workbook_Page_64.jpg"),
];

export const NUR_21_50 = [
  require("./Nur_21_50/Nur_21_50_Page_01.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_02.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_03.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_04.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_05.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_06.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_07.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_08.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_09.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_10.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_11.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_12.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_13.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_14.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_15.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_16.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_17.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_18.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_19.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_20.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_21.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_22.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_23.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_24.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_25.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_26.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_27.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_28.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_29.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_30.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_31.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_32.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_33.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_34.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_35.jpg"),
  require("./Nur_21_50/Nur_21_50_Page_36.jpg"),
];

export const NUR_ABCD_CAPS = [
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_01.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_02.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_03.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_04.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_05.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_06.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_07.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_08.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_09.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_10.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_11.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_12.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_13.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_14.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_15.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_16.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_17.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_18.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_19.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_20.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_21.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_22.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_23.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_24.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_25.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_26.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_27.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_28.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_29.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_30.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_31.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_32.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_33.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_34.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_35.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_36.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_37.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_38.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_39.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_40.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_41.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_42.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_43.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_44.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_45.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_46.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_47.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_48.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_49.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_50.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_51.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_52.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_53.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_54.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_55.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_56.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_57.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_58.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_59.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_60.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_61.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_62.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_63.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_64.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_65.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_66.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_67.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_68.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_69.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_70.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_71.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_72.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_73.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_74.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_75.jpg"),
  require("./Nur_ABCD_Caps/Nur_ABCD_Caps_Page_76.jpg"),
];

export const NUR_ABCD_CAPS_WORKBOOK = [
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_01.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_02.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_03.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_04.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_05.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_06.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_07.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_08.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_09.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_10.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_11.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_12.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_13.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_14.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_15.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_16.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_17.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_18.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_19.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_20.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_21.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_22.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_23.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_24.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_25.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_26.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_27.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_28.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_29.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_30.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_31.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_32.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_33.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_34.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_35.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_36.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_37.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_38.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_39.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_40.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_41.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_42.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_43.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_44.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_45.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_46.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_47.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_48.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_49.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_50.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_51.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_52.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_53.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_54.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_55.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_56.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_57.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_58.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_59.jpg"),
  require("./Nur_ABCD_Caps_workbook/Nur_ABCD_Caps_workbook_Page_60.jpg"),
];

export const NUR_ABCD_SMALL = [
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_01.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_02.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_03.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_04.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_05.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_06.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_07.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_08.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_09.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_10.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_11.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_12.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_13.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_14.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_15.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_16.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_17.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_18.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_19.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_20.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_21.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_22.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_23.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_24.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_25.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_26.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_27.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_28.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_29.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_30.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_31.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_32.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_33.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_34.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_35.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_36.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_37.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_38.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_39.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_40.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_41.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_42.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_43.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_44.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_45.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_46.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_47.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_48.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_49.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_50.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_51.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_52.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_53.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_54.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_55.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_56.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_57.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_58.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_59.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_60.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_61.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_62.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_63.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_64.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_65.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_66.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_67.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_68.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_69.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_70.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_71.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_72.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_73.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_74.jpg"),
  require("./Nur_ABCD_small/Nur_ABCD_small_Page_75.jpg"),
];

export const NUR_ABCD_SMAL_WORKBOOK = [
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_01.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_02.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_03.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_04.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_05.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_06.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_07.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_08.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_09.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_10.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_11.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_12.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_13.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_14.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_15.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_16.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_17.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_18.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_19.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_20.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_21.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_22.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_23.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_24.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_25.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_26.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_27.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_28.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_29.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_30.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_31.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_32.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_33.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_34.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_35.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_36.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_37.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_38.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_39.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_40.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_41.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_42.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_43.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_44.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_45.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_46.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_47.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_48.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_49.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_50.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_51.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_52.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_53.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_54.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_55.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_56.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_57.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_58.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_59.jpg"),
  require("./Nur_ABCD_smal_workbook/Nur_ABCD_smal_workbook_Page_60.jpg"),
];

export const NUR_ART_AND_CRAFT = [
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_01.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_02.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_03.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_04.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_05.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_06.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_07.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_08.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_09.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_10.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_11.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_12.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_13.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_14.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_15.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_16.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_17.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_18.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_19.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_20.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_21.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_22.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_23.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_24.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_25.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_26.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_27.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_28.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_29.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_30.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_31.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_32.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_33.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_34.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_35.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_36.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_37.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_38.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_39.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_40.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_41.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_42.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_43.jpg"),
  require("./Nur_art_and_craft/Nur_art_and_craft_Page_44.jpg"),
];

export const NUR_ASSESSMENT = [
  require("./Nur_assessment/Nur_assessment_Page_01.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_02.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_03.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_04.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_05.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_06.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_07.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_08.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_09.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_10.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_11.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_12.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_13.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_14.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_15.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_16.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_17.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_18.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_19.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_20.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_21.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_22.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_23.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_24.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_25.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_26.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_27.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_28.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_29.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_30.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_31.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_32.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_33.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_34.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_35.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_36.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_37.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_38.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_39.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_40.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_41.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_42.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_43.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_44.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_45.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_46.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_47.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_48.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_49.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_50.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_51.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_52.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_53.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_54.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_55.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_56.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_57.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_58.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_59.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_60.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_61.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_62.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_63.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_64.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_65.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_66.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_67.jpg"),
  require("./Nur_assessment/Nur_assessment_Page_68.jpg"),
];

export const NUR_EVS = [
  require("./Nur_EVS/Nur_EVS_Page_01.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_02.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_03.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_04.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_05.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_06.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_07.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_08.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_09.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_10.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_11.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_12.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_13.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_14.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_15.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_16.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_17.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_18.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_19.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_20.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_21.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_22.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_23.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_24.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_25.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_26.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_27.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_28.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_29.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_30.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_31.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_32.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_33.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_34.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_35.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_36.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_37.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_38.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_39.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_40.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_41.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_42.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_43.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_44.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_45.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_46.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_47.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_48.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_49.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_50.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_51.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_52.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_53.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_54.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_55.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_56.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_57.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_58.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_59.jpg"),
  require("./Nur_EVS/Nur_EVS_Page_60.jpg"),
];

export const NUR_LTI_CAPS = [
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_01.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_02.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_03.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_04.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_05.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_06.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_07.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_08.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_09.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_10.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_11.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_12.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_13.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_14.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_15.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_16.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_17.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_18.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_19.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_20.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_21.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_22.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_23.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_24.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_25.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_26.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_27.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_28.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_29.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_30.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_31.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_32.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_33.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_34.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_35.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_36.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_37.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_38.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_39.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_40.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_41.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_42.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_43.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_44.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_45.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_46.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_47.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_48.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_49.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_50.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_51.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_52.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_53.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_54.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_55.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_56.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_57.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_58.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_59.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_60.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_61.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_62.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_63.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_64.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_65.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_66.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_67.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_68.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_69.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_70.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_71.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_72.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_73.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_74.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_75.jpg"),
  require("./Nur_LTI_Caps/Nur_LTI_Caps_Page_76.jpg"),
];

export const NUR_LTI_CAPS_WORKBOOK = [
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_01.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_02.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_03.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_04.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_05.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_06.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_07.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_08.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_09.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_10.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_11.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_12.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_13.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_14.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_15.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_16.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_17.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_18.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_19.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_20.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_21.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_22.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_23.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_24.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_25.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_26.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_27.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_28.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_29.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_30.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_31.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_32.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_33.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_34.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_35.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_36.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_37.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_38.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_39.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_40.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_41.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_42.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_43.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_44.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_45.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_46.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_47.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_48.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_49.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_50.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_51.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_52.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_53.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_54.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_55.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_56.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_57.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_58.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_59.jpg"),
  require("./Nur_LTI_Caps_workbook/Nur_LTI_Caps_workbook_Page_60.jpg"),
];

export const NUR_RHYMES_AND_STORIES = [
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_01.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_02.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_03.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_04.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_05.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_06.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_07.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_08.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_09.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_10.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_11.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_12.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_13.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_14.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_15.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_16.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_17.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_18.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_19.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_20.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_21.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_22.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_23.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_24.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_25.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_26.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_27.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_28.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_29.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_30.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_31.jpg"),
  require("./Nur_Rhymes_&_Stories/Nur_Rhymes_&_Stories_Page_32.jpg"),
];

export const NUR_SATPIN_SMALL = [
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_01.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_02.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_03.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_04.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_05.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_06.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_07.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_08.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_09.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_10.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_11.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_12.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_13.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_14.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_15.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_16.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_17.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_18.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_19.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_20.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_21.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_22.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_23.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_24.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_25.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_26.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_27.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_28.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_29.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_30.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_31.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_32.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_33.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_34.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_35.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_36.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_37.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_38.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_39.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_40.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_41.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_42.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_43.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_44.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_45.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_46.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_47.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_48.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_49.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_50.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_51.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_52.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_53.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_54.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_55.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_56.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_57.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_58.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_59.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_60.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_61.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_62.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_63.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_64.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_65.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_66.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_67.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_68.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_69.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_70.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_71.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_72.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_73.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_74.jpg"),
  require("./Nur_SATPIN small/Nur_SATPIN small_Page_75.jpg"),
];
